process.roles=broker,controller

node.id=1

# Kafka it is through what names (host) applications communicate with each other
# must be the same as hostname in docker-compose
controller.quorum.voters=1@kafka:9093

# PLAINTEXT is a default Kafka's protocol without SSL
# CONTROLLER is a custom name for port 9093 
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093


advertised.listeners=PLAINTEXT://kafka:9092

# Match of custom name
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

# Specifies by what name transfer service traffic
controller.listener.names=CONTROLLER

# Storage
log.dirs=/var/lib/kafka/data

# Single node cluster setting
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

# Disable auto topic creation
auto.create.topics.enable=false